setting:
  shared_memory_name: "exp_dummy"

source:
  type: "FolderImageSource"
  folder_path: assets/images
  fps: 20
  pattern: "*.jpg"
  recursive: true
  sort: "natsort"
  loop: False
  start_index: 0

pipelines:
  - name: "DummyPipeline"
    enable: true
    gpu_id: 0
    
    detector:
      type: "Yolo11Detector"
      weights_path: assets/weights/head_yolox_1024_best.pt
      imgsz: 1024
      iou: 0.7
      conf: 0.25
      classes: [1]

    tracker:
      type: "OCSortTracker"
      det_thresh: 0.01
      iou_threshold: 0.2
      max_age: 90
      min_hits: 5
      inertia: 0.4
      classes: [head]

    abandoned:
      type: "abandonedObject"
      dist_threshold : 0.05
      static_dist_threshold : 0.01

      suspected_threshold_min : 0.1
      lost_threshold_min : 0.1
      unassigned_threshold_min : 5

      clean_threshold_sec : 30
      prev_clean_threshold_sec : 2

      score_threshold : 0.7
      restore_threshold : 0.7
      owner_frame_threshold : 30
      move_threshold_sec : 1
      iou_threshold : 0.75
      fps: 30

output:
  mode: "sync"
  target_fps: 30
  
  handlers:
    - type: "ScreenHandler"
      enable: true
      window_name: "MOT Monitor"
      view_width: 960
      view_height: 540
      draw_detections: true
      draw_tracks: true
      show_info: true
    - type: "FileLogHandler"
      enable: true
      output_dir: "./logs"
      filename: "tracking_data.csv"