setting:
  shared_memory_name: "exp_dummy"

source:
  type: "FolderImageSource"
  folder_path: assets/images
  fps: 30
  pattern: "*.jpg"
  recursive: true
  sort: "name"
  loop: true
  start_index: 0

pipelines:
  - name: "DummyPipeline"
    enable: true
    gpu_id: 0
    
    detector:
      type: "YOLOWorldDetector"
      weights_path: assets/weights/yolov8s-world.pt
      imgsz: 640
      iou: 0.7
      conf: 0.5
      classes: [person, bag]
      
    tracker:
      type: "BYTETracker"
      track_thresh : 0.5
      match_thresh : 0.8
      track_buffer : 30
      crowd : false
      fps: 30
      classes: [person, bag]

    abandoned:
      type: "abandonedObject"
      dist_threshold : 0.08
      static_dist_threshold : 0.01

      suspect_threshold_min : 15
      lost_threshold_min : 15
      unassigned_threshold_min : 5

      clean_threshold_sec : 3
      prev_clean_threshold_sec : 2

      score_threshold : 0.7
      restore_threshold : 0.7
      owner_frame_threshold : 30
      move_threshold_sec : 1
      iou_threshold : 0.75
      fps: 30

output:
  mode: "sync"
  target_fps: 30
  
  handlers:
    - type: "ScreenHandler"
      enable: true
      window_name: "MOT Monitor"
      view_width: 480
      view_height: 270
      draw_detections: true
      draw_tracks: true
      show_info: true
    - type: "FileLogHandler"
      enable: true
      output_dir: "./logs"
      filename: "tracking_data.csv"