setting:
  shared_memory_name: "exp_dummy"

source:
  type: "VideoSource"
  video_path: "assets/videos/sep.mp4"
  loop: False
  fps: 30

pipelines:
  - name: "DummyPipeline"
    enable: true
    gpu_id: 0
    
    detector:
      type: "Yolo11Detector"
      weights_path: assets/weights/yolo11s.pt
      imgsz: 2176
      iou: 0.7
      conf: 0.25
      classes: [0, 24, 26]
      
    tracker:
      type: "BYTETracker"
      track_thresh : 0.25
      match_thresh : 0.7
      track_buffer : 60
      crowd : false
      fps: 30
      classes: [person, handbag, backpack]

    abandoned:
      type: "abandonedObject"
      dist_threshold : 0.15
      static_dist_threshold : 0.01

      suspect_threshold_min : 0.1
      lost_threshold_min : 0.1
      unassigned_threshold_min : 0.1

      clean_threshold_sec : 30
      prev_clean_threshold_sec : 2

      score_threshold : 0.7
      restore_threshold : 0.7
      owner_frame_threshold : 30
      move_threshold_sec : 1
      iou_threshold : 0.75
      fps: 30

output:
  mode: "sync"
  target_fps: 30
  
  handlers:
    - type: "ScreenHandler"
      enable: true
      window_name: "MOT Monitor"
      view_width: 960
      view_height: 540
      draw_detections: true
      draw_tracks: true
      show_info: true
    - type: "FileLogHandler"
      enable: true
      output_dir: "./logs"
      filename: "tracking_data.csv"