setting:
  shared_memory_name: "exp_dummy"

source:
  type: "WebcamSource"
  device_index: 0
  width: 1280
  height: 720
  fps: 30
  buffer_size: 60

pipelines:
  - name: "DummyPipeline"
    enable: true
    gpu_id: 0
    
    detector:
      type: "Yolo11Detector"
      weights_path: assets/weights/best.pt
      imgsz: 1280
      iou: 0.7
      conf: 0.4
      classes: [0, 1, 2, 3]
      
    tracker:
      type: "BYTETracker"
      track_thresh : 0.4
      match_thresh : 0.7
      track_buffer : 30
      crowd : false
      fps: 30
      classes: [person, head, handbag, backpack]

    abandoned:
      type: "abandonedObject"
      dist_threshold : 0.5
      static_dist_threshold : 0.01

      suspected_threshold_min : 0.1
      lost_threshold_min : 0.1
      unassigned_threshold_min : 3

      clean_threshold_sec : 30
      prev_clean_threshold_sec : 2

      score_threshold : 0.7
      restore_threshold : 0.7
      owner_frame_threshold : 30
      move_threshold_sec : 1
      iou_threshold : 0.75
      fps: 30

output:
  mode: "sync"
  target_fps: 30
  
  handlers:
    - type: "ScreenHandler"
      enable: true
      window_name: "MOT Monitor"
      view_width: 960
      view_height: 540
      draw_detections: true
      draw_tracks: true
      show_info: true
    - type: "FileLogHandler"
      enable: true
      output_dir: "./logs"
      filename: "tracking_data.csv"