setting:
  shared_memory_name: "exp_dummy"

source:
  type: "DummySource"
  width: 1280
  height: 720
  fps: 30
  buffer_size: 60

pipelines:
  - name: "DummyPipeline"
    enable: true
    gpu_id: 0
    
    detector:
      type: "DummyDetector"
      img_width: 640
      img_height: 360
      conf_thres: 0.5
      
    tracker:
      type: "DummyTracker"
      fps: 30

output:
  mode: "sync"
  target_fps: 30
  
  handlers:
    - type: "ScreenHandler"
      enable: true
      window_name: "MOT Monitor"
      view_width: 480
      view_height: 270
      draw_detections: true
      draw_tracks: true
      show_info: true
    - type: "FileLogHandler"
      enable: true
      output_dir: "./logs"
      filename: "tracking_data.csv"