setting:
  project_name: "Multi-Webcam-Separate-Windows"

sources:
  - id: "cam_10"
    type: "VideoSource"
    video_path: "assets/videos/fps30_output.mp4"
    shared_memory_name: "shm_cam_10"
    width: 640
    height: 480
    fps: 30
    buffer_size: 30
    loop : true

pipelines:
  - name: "Office10_Cam"
    source_id: "cam_10"
    enable: true
    gpu_id: 0

    detector:
      type: "Yolo11Detector"
      weights_path: assets/weights/yolo11n.pt
      imgsz: 640
      iou: 0.7
      conf: 0.5
      classes: 0
      
    tracker:
      type: "BYTETracker"
      track_thresh : 0.5
      match_thresh : 0.8
      track_buffer : 30
      crowd : false
      fps: 30
      classes: ["person", "bag", "laptop", "keyboard", "mouse"]

    abandoned:
      type: "abandonedObject"
      dist_threshold : 0.08
      static_dist_threshold : 0.01

      suspect_threshold_min : 15
      lost_threshold_min : 15
      unassigned_threshold_min : 5

      clean_threshold_sec : 3
      prev_clean_threshold_sec : 2

      score_threshold : 0.7
      restore_threshold : 0.7
      owner_frame_threshold : 30
      iou_threshold : 0.75
      fps: 30      

output:
  mode: "sync"
  handlers:
    - type: "ScreenHandler"
      enable: true
      view_width: 1280
      view_height: 960
      draw_detections: true
      draw_tracks: true
      show_info: true

    - type: "FileLogHandler"
      enable: true
      output_dir: "./logs"
      filename: "tracking_data.csv"

    - type: "WebHandler"
      enable: true
      port: 5000
      view_width: 1280  
      view_height: 960
      draw_detections: true
      draw_tracks: true
      show_info: true
